version: "3.8"

services:
  postgres:
    container_name: picpay_challenge_pg
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: pic_challenge
    volumes:
      - picpay_challenge_pg_data:/bitnami/postgresql

volumes:
  picpay_challenge_pg_data:
